import type { Project } from "@/types/portfolio";

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: "prince-ecommerce",
    title: "Prince E-Commerce",
    category: "Full Stack",
    type: "Full Stack Web App",
    description:
      "An online store built with Laravel 12, Livewire 3, and Filament 5. Tracks stock by product variant and size, merges guest carts on sign-in, and handles payments through Midtrans Snap. Includes an admin panel for orders and inventory.",
    tags: ["Laravel 12", "Livewire 3", "Filament 5", "MySQL", "Midtrans", "PHP"],
    githubUrl: "https://github.com/rasatshq/prince-ecommerce",
    image: "/prince-ecommerce.png",
    accent: "from-violet-500/10 via-purple-500/[0.03] to-white",
    glow: "hover:border-violet-500/50 hover:shadow-violet-500/10",
  },
  {
    id: "photobooth-online",
    title: "Photobooth Online",
    category: "Frontend",
    type: "4-Shot Photostrip Web App",
    description:
      "A free browser-based photobooth that captures four photos from a phone or laptop camera, lets users choose an aesthetic photostrip frame, then download and share the result without signing in.",
    tags: ["4-Shot Photostrip", "Web Camera", "Frame Selection", "No Login"],
    githubUrl: "https://github.com/rasatshq/photobooth-online",
    image: "/photobooth-online.png",
    imageWidth: 1902,
    imageHeight: 907,
    accent: "from-fuchsia-500/10 via-violet-500/[0.03] to-white",
    glow: "hover:border-fuchsia-500/50 hover:shadow-fuchsia-500/10",
  },
  {
    id: "aplikasi-pos-kasir",
    title: "Aplikasi POS Kasir",
    category: "Frontend",
    type: "Web POS System",
    description:
      "A browser-based cashier application built with JavaScript. Handles product transactions, calculates order totals, and manages checkout in a responsive interface.",
    tags: ["JavaScript", "HTML5", "CSS3", "POS System"],
    githubUrl: "https://github.com/rasatshq/Aplikasi-Pos-kasir",
    image: "/aplikasi-pos-kasir.png",
    imageWidth: 1887,
    imageHeight: 897,
    accent: "from-cyan-500/10 via-teal-500/[0.03] to-white",
    glow: "hover:border-cyan-500/50 hover:shadow-cyan-500/10",
  },
  {
    id: "cafe-manjaro",
    title: "Cafe Manjaro Web Interface",
    category: "Frontend",
    type: "Interactive POS & UI",
    description:
      "A cashier system and cafe landing page with a dark interface. Supports order workflows across desktop and mobile screens.",
    tags: ["HTML5", "CSS3", "JavaScript"],
    githubUrl: "https://github.com/rasatshq/cafe-manjaro",
    image: "/cafe-manjaro.png",
    imageWidth: 1899,
    imageHeight: 901,
    accent: "from-cyan-500/10 via-blue-500/[0.03] to-white",
    glow: "hover:border-cyan-500/50 hover:shadow-cyan-500/10",
  },
  {
    id: "interactive-music-player",
    title: "Interactive Web Music Player",
    category: "Frontend",
    type: "Audio Web App",
    description:
      "A responsive web-based interactive music player featuring dynamic audio playback controls, sleek UI/UX aesthetics, and structured local asset pathing.",
    tags: ["JavaScript", "HTML5", "CSS3", "Audio UI"],
    accent: "from-amber-500/10 via-orange-500/[0.03] to-white",
    glow: "hover:border-amber-500/50 hover:shadow-amber-500/10",
  },
  {
    id: "network-architecture-lab",
    title: "Network Architecture & Security Lab",
    category: "Networking",
    type: "Cisco Infrastructure",
    description:
      "Enterprise-scale network topology design in Cisco Packet Tracer incorporating Variable Length Subnet Masking (VLSM) and switch port security protocols.",
    tags: ["Cisco Packet Tracer", "VLSM", "Port Security", "CCNA"],
    accent: "from-emerald-500/10 via-teal-500/[0.03] to-white",
    glow: "hover:border-emerald-500/50 hover:shadow-emerald-500/10",
  },
  {
    id: "judol-sentinel",
    title: "Judol Sentinel",
    category: "Data Science",
    type: "NLP / Deep Learning",
    description:
      "Deep Learning text classification system using Bidirectional LSTM to detect Indonesian online gambling (judol) promotions. Features a de-obfuscation pipeline to handle intentionally mangled text, trained on a real Indonesian dataset, and deployed as a Cyber SOC monitoring dashboard with Streamlit.",
    tags: ["Python", "BiLSTM", "Keras", "Streamlit", "NLP", "Deep Learning"],
    githubUrl: "https://github.com/rasatshq/indonesian-judol-bilstm",
    accent: "from-rose-500/10 via-red-500/[0.03] to-white",
    glow: "hover:border-rose-500/50 hover:shadow-rose-500/10",
  },
  {
    id: "data-science-processing-lab",
    title: "Data Science & Processing Lab",
    category: "Data Science",
    type: "Data Pipeline",
    description:
      "Raw dataset cleaning (data scrubbing), missing/anomaly value handling, and exploratory data analysis using Python and the NumPy ecosystem.",
    tags: ["Python", "NumPy", "Data Scrubbing", "EDA"],
    accent: "from-indigo-500/10 via-purple-500/[0.03] to-white",
    glow: "hover:border-indigo-500/50 hover:shadow-indigo-500/10",
  },
];
